export const data = {
  nav_options: [
    { name: "Overview", _id: "overview", location: "/overview" },
    { name: "Bodies", _id: "tanks", location: "/tanks" },
    // { name: "Sensors", _id: "sensors", location: "/sensors" },
  ],

  tank_info: [
    {
      tank_id: "1101",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },

    {
      tank_id: "1102",
      lcoation: "Zone D",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1103",
      lcoation: "Zone B",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1104",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1105",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1106",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1107",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1108",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1109",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1110",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1111",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1112",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1113",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1114",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1115",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1116",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1117",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1118",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1119",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1120",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1121",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1122",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1123",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
  ],
  bodies_info: [
    {
      tank_id: "1101",
      lcoation: "level 4",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "dam",
      volume: "22.4",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },

    {
      tank_id: "1102",
      lcoation: "level 9",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "sump",
      volume: "16",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1103",
      lcoation: "Level 10",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "dam",
      volume: "72",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1104",
      lcoation: "level 13",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "sump",
      volume: "25.6",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1105",
      lcoation: "level 17",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "dam",
      volume: "70.5",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1106",
      lcoation: "level 19",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "sump",
      volume: "100",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1107",
      lcoation: "level 2",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "dam",
      volume: "13.7",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1108",
      lcoation: "level 1",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "sump",
      volume: "10",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1109",
      lcoation: "level 4",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "dam",
      volume: "28.9",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1110",
      lcoation: "level 4",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "sump",
      volume: "34.7",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1111",
      lcoation: "level 5",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "dam",
      volume: "30",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1112",
      lcoation: "level 7",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "sump",
      volume: "14.4",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1113",
      lcoation: "level 8",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "dam",
      volume: "43.6",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1114",
      lcoation: "level 20",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "sump",
      volume: "43.6",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1115",
      lcoation: "level 4",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "dam",
      volume: "43.6",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1116",
      lcoation: "level 4",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "sump",
      volume: "43.6",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1117",
      lcoation: "level 4",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "dam",
      volume: "43.6",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1118",
      lcoation: "level 4",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "sump",
      volume: "43.6",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1119",
      lcoation: "level 4",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "dam",
      volume: "43.6",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1120",
      lcoation: "level 4",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "sump",
      volume: "43.6",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1121",
      lcoation: "level 4",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "dam",
      volume: "43.6",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1122",
      lcoation: "level 4",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "sump",
      volume: "43.6",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1123",
      lcoation: "level 4",
      status: "low",
      content: "water",
      percentage: "16%",
      name: "dam",
      volume: "43.6",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
  ],
};
