export const data = {
  nav_options: [
    { name: "Overview", _id: "overview", location: "/overview" },
    { name: "Tanks", _id: "tanks", location: "/tanks" },
    // { name: "Sensors", _id: "sensors", location: "/sensors" },
  ],

  tank_info: [
    {
      tank_id: "1101",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },

    {
      tank_id: "1102",
      lcoation: "Zone D",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1103",
      lcoation: "Zone B",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1104",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1105",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1106",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1107",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1108",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1109",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1110",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1111",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1112",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1113",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1114",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1115",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1116",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1117",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1118",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1119",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1120",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1121",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1122",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
    {
      tank_id: "1123",
      lcoation: "Zone A",
      status: "low",
      content: "water",
      percentage: "16%",
      volume: "11404",
      order: "Refill",
      last_used: "07/21/14 14:40pm",
    },
  ],
};
